ProjectLighthouseCAU/luna

src/api/auth/LighthouseAuthApi.ts
I added the ApiToken, ApiRole and ApiRegistrationKey types and finished the implementation of signUp, logIn, logOut, getAllUsers and getToken for the new authentication API (heimdall).
=> Define other API types and finish the implementation of LighthouseAuthApi

src/components/RouteLink.tsx
This adds an animation to the sidebar (based on [this example](https://codesandbox.io/s/framer-motion-accordion-qx958)):
https://github.com/user-attachments/assets/1ea9d914-907b-4882-a3f9-93a4781886cd
Marked as a draft, since it still seems to be a bit buggy and occasionally trigger page refreshes, both in Chrome and Firefox (why does this happen?).
=> Animate the sidebar collapses

package-lock.json, package.json
This removes the metrics types upstream and possibly (?) addresses #61.
=> Bump nighthouse to 3.0.3 and pin it

src/screens/home/admin/MonitorInspector.tsx, src/screens/home/admin/MonitorInspectorLampsCard.tsx, src/screens/home/admin/MonitorInspectorRoomCard.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/admin/helpers/MonitorCriterion.ts, src/screens/home/admin/helpers/MonitorFilter.ts, src/utils/rgb.ts
As initially suggested in #5, this adds support for monitoring arbitrary quantities visually:
https://github.com/user-attachments/assets/b348c570-dfdf-4a17-bcb7-2109297469ba
- We'll use simple normalization (ignoring `null` or `undefined` values) for now
=> Add support for monitoring arbitrary properties visually

package-lock.json, package.json, src/contexts/api/model/ModelContext.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/admin/ResourcesContentsView.tsx, src/screens/home/admin/ResourcesToolbar.tsx, src/screens/home/admin/ResourcesTreeView.tsx, src/screens/home/admin/ResourcesView.tsx, src/utils/result.ts
This implements the resources view for admins, which provides a file browser-like UI for viewing the resource tree:
- Let the user expand multiple nodes in list view (see the todo comment)
=> Implement resources view

src/components/ContextMenu.tsx, src/contexts/api/model/ModelContext.tsx, src/screens/home/admin/ResourcesTreeView.tsx
This improves the resource context menu by adding the option to download the resource as a JSON file and to rename it:
Additionally, deletions must now be confirmed via a modal to avoid accidental deletions (potentially of entire directory trees):
=> Improve resource context menu

src/screens/home/admin/MonitorView.tsx
This changes the breakpoint between column/row layout to 2xl, which should ensure that the cards always fit onto the screen.
=> Fix monitoring cards layout on smaller devices

src/components/Display.tsx
This fixes the mouse coordinate conversion in `Display` on high-DPI displays (e.g. modern phones), see https://stackoverflow.com/a/33063222.
=> Fix mouse coordinate conversion on high DPI displays

package-lock.json, package.json, src/App.tsx, src/components/BooleanCheck.tsx, src/components/BooleanChip.tsx, src/components/ObjectInspectorTable.tsx, src/components/ObjectInspectorValue.tsx, src/components/RouteLink.tsx, src/constants/LocalStorageKey.ts, src/contexts/api/model/ModelContext.tsx, src/contexts/env/ClientIdContext.tsx, src/hooks/useEventListener.ts, src/screens/home/admin/MonitorInspectorLampsCard.tsx, src/screens/home/admin/MonitorInspectorRoomCard.tsx, src/screens/home/admin/MonitorInspectorValue.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/admin/ResourcesContentsView.tsx, src/screens/home/admin/ResourcesTreeView.tsx, src/screens/home/admin/ResourcesView.tsx, src/screens/home/displays/DisplayInspector.tsx, src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayView.tsx, src/screens/home/displays/helpers/InputConfig.ts, src/screens/home/displays/helpers/InputState.ts, src/utils/motion.ts, src/utils/vec2.ts
This adds support for mouse, keyboard and controller input, both via the [legacy API](https://github.com/ProjectLighthouseCAU/nighthouse/blob/62bce4d1fc73f45e1fdd17bf3c3946aeba9f8bb0/src/common/protocol/input/legacy.ts) (via `user/<user>/model`) and the [new input API](https://github.com/ProjectLighthouseCAU/nighthouse/blob/62bce4d1fc73f45e1fdd17bf3c3946aeba9f8bb0/src/common/protocol/input/new.ts) (via `user/<user>/input`).
=> Add support for mouse, keyboard and controller input

package-lock.json, package.json
Nighthouse 4.2.0 removes client-side demultiplexing in favor of having the server handle streams on the same resource.
=> Bump nighthouse to 4.2.0

src/screens/home/displays/DisplayInspectorInputCard.tsx
This fixes the modifier views, which previously referenced the old properties, and moves them to a new `KeyModifiersView`.
=> Fix and factor out modifiers view in inspector

src/screens/home/displays/DisplayView.tsx
The problem was that later iterations of our polling loop could interleave with earlier ones (at `await` points) and still see the old `lastStates`, since we assigned it after pushing the changes to the API (asynchronously).
This fixes the issue by moving the assignment prior to any `await` points and adds an explanatory comment.
=> Fix duplicate gamepad events

src/components/SearchBar.tsx, src/hooks/useVisibleRoutes.tsx, src/modals/QuickSwitcherModal.tsx, src/screens/home/HomeScreen.tsx, src/screens/home/sidebar/Sidebar.tsx, src/screens/home/sidebar/SidebarRoutes.tsx
This adds a quick switcher to LUNA, triggered by the conventional <kbd>Cmd/Ctrl</kbd> + <kbd>K</kbd> shortcut, known from Discord, Spotify and other apps, making it quick and easy to navigate the site using the keyboard:
https://github.com/user-attachments/assets/55b96755-7dbd-4d83-acce-3ee82f83e569
(maybe we should document this shortcut somewhere)
=> Add quick switcher (and factor out useVisibleRoutes hook)

src/hooks/useVisibleRoutes.tsx, src/screens/home/sidebar/SidebarRoutes.tsx
This avoid a 'jumpy' layout with e.g. nested admin routes collapsing when leaving the viewport.
=> Disable lazy loading for static routes in sidebar

src/modals/QuickSwitcherModal.tsx
The text was black on blue, which isn't great to read, hence this PR applies the same color as we do in the sidebar
=> Fix the text color in the quick switcher under light mode

src/components/DisplayCard.tsx, src/components/DisplayPinLabel.tsx, src/components/DisplayRouteLabel.tsx, src/components/RouteLink.tsx, src/contexts/env/ColorSchemeContext.tsx, src/hooks/useLiveUser.ts, src/hooks/usePinnedDisplays.ts, src/hooks/useVisibleRoutes.tsx, src/modals/QuickSwitcherModal.tsx, src/screens/home/displays/DisplayGrid.tsx, src/screens/home/sidebar/SidebarRoutes.tsx
This pins the current live user to the top of the display list and includes some refactorings under the hood to make these pinned displays more easily accessible (via a new `usePinnedDisplays` hook):
This implements part 1 of #97.
=> Add pinned live user and show pinned users in display grid

src/contexts/api/model/ModelContext.tsx, src/hooks/useLaserMetrics.ts, src/screens/home/admin/MonitorView.tsx
Hooks seem to be a better abstraction for this than exposing the specific paths in the model context, so let's do it this way.
=> Add `useLaserMetrics` hook

src/App.tsx, src/utils/uuid.ts
This is mostly useful for testing LUNA on the local network where HTTPS isn't available, but might also help if the browser doesn't support this particular API.
=> Add fallback for `crypto.randomUUID`

src/components/ContextMenu.tsx, src/index.css
This adds a custom context menu implementation that triggers on long touches and doesn't interfere with normal events.
=> Activate context menu on long touches

src/components/DisplayActionsMenu.tsx, src/components/DisplayContextMenu.tsx, src/screens/home/displays/DisplayInspector.tsx, src/screens/home/displays/DisplayInspectorActionsCard.tsx, src/screens/home/displays/DisplayInspectorApiTokenCard.tsx
This exposes the display's actions as a card in the display inspector:
The underlying representation is shared with the context menu and has been factored out into a generic `<DisplayActionsMenu>` component.
=> Add "Actions" card to display inspector

src/contexts/api/model/ModelContext.tsx, src/modals/ApiTokenModal.tsx, src/screens/home/displays/DisplayInspector.tsx, src/screens/home/displays/DisplayInspectorApiTokenCard.tsx
This lets admins view and regenerate other users' tokens too
=> Show viewed display's API token rather than the own token

src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayView.tsx, src/screens/home/displays/helpers/InputConfig.ts
This makes the switches slightly smaller and makes sure the UI consistently refers to game controllers as "gamepads"
=> Refine the input card UI

src/screens/home/sidebar/Sidebar.tsx
Passing this method directly resulted in a strange bug, not caught by TypeScript's type system:
- `auth.cycleToken` has type `(id?: number) => void`
- `UserSnippet` takes `() => void`
- The actual downstream component takes `(e: SomeEvent) => void`
For some reason TypeScript considered these conversions to be safe, even though the event object ended up being passed as a number parameter, which definitely isn't safe. Hence why we wrap it in a callback here.
=> Fix token cycling bug

src/hooks/useLocalStorage.ts
This effectively 'repairs' data in users' local storage, by only keeping data under known keys, making it more robust against schema changes. The known keys are determined by the default value, which is used whenever there's a mismatch.
=> Merge values in `useLocalStorage`

src/screens/home/displays/DisplayView.tsx
The manual add logic seems to be error-prone, hence why absolute events are probably better.
=> Emit absolute orientation/motion events

src/screens/home/displays/DisplayView.tsx, src/screens/home/displays/helpers/InputConfig.ts
We should lower the rate a bit further. We'll also make it non-configurable for now, since the rate will otherwise be persisted, even if our defaults change.
=> Increase orientation/motion event interval to 100ms

src/screens/home/displays/DisplayView.tsx
iOS Safari seems to yield absolute events here anyway and doesn't understand `deviceorientationabsolute`.
=> Use regular deviceorientation event key again

src/components/AnimatedPresence.tsx, src/components/RouteLink.tsx, src/components/TitledCard.tsx, src/screens/home/displays/DisplayInspector.tsx, src/screens/home/displays/DisplayInspectorActionsCard.tsx, src/screens/home/displays/DisplayInspectorApiTokenCard.tsx, src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayInspectorOptionsCard.tsx
This adds support for collapsible `TitledCard`s:
https://github.com/user-attachments/assets/bb54c04d-143f-4ade-872b-a754a120a28f
=> Make inspector cards collapsible

src/components/ObjectInspectorTable.tsx, src/components/TimeInterval.tsx, src/screens/home/HomeContent.tsx, src/screens/home/HomeScreen.tsx, src/screens/home/admin/MonitorInspectorLampsCard.tsx, src/screens/home/admin/MonitorInspectorRoomCard.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/displays/DisplayView.tsx, src/screens/home/helpers/HomeContentLayout.ts
This adds a new customizable layout property to `HomeContent` for content that chooses to span the entire screen, which constrains the content to the browser height. This makes it possible to e.g. nest scroll containers which otherwise would have grown beyond the viewport.
=> Improve full screen layout for home content

src/screens/home/displays/DisplayView.tsx
The long title doesn't fit on small phone screens.
=> Only include the username in the display title in compact layout

src/hooks/useVisibleRoutes.tsx, src/screens/home/sidebar/SidebarRoutes.tsx
In compact mode, the current display may be hidden in the menu, which can be confusing UX-wise. This patch therefore makes sure that the current display is always shown.
=> Always show the current display in the visible routes

src/components/SearchBar.tsx, src/hooks/useVisibleRoutes.tsx, src/screens/home/displays/DisplaysToolbar.tsx, src/screens/home/sidebar/SidebarRoutes.tsx
This fixes a slightly confusing UX issue where not all displays would be displayed, because the user added a filter in the display grid.
=> Add button for clearing display search query to visible routes/sidebar
