package-lock.json, package.json
This fixes #54, an issue where deferred errors would not get caught correctly.
=> Bump nighthouse to 3.0.2

src/contexts/api/model/ModelContext.tsx, src/contexts/api/model/types/LaserMetrics.ts, src/contexts/api/model/types/index.ts
As per https://github.com/ProjectLighthouseCAU/nighthouse/issues/8
=> Move LaserMetrics types to LUNA

src/components/Display.tsx, src/contexts/api/model/types/LaserMetrics.ts, src/screens/home/admin/MonitorInspector.tsx, src/screens/home/admin/MonitorInspectorLampsCard.tsx, src/screens/home/admin/MonitorInspectorRoomCard.tsx, src/screens/home/admin/MonitorInspectorTable.tsx, src/screens/home/admin/MonitorInspectorValue.tsx, src/screens/home/admin/MonitorView.tsx, src/utils/vec2.ts
This cleans up the monitoring view a bit:
=> Clean up the monitoring view

src/components/Display.tsx, src/contexts/api/model/types/LaserMetrics.ts, src/screens/home/admin/MonitorInspector.tsx, src/screens/home/admin/MonitorInspectorRoomCard.tsx, src/screens/home/admin/MonitorInspectorTable.tsx, src/screens/home/admin/MonitorInspectorValue.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/admin/helpers/FlatRoomV2Metrics.ts, src/utils/bounded.ts
Some preparatory work to add support for filtering the monitor view by arbitrary keys.
=> Improve coordinate conversion and refactor monitoring view slightly

package-lock.json, package.json, src/components/ContextMenu.tsx, src/components/SearchBar.tsx, src/components/SimpleEditForm.tsx, src/contexts/api/model/ModelContext.tsx, src/screens/home/admin/ResourcesContentsView.tsx, src/screens/home/admin/ResourcesTreeView.tsx, src/screens/home/admin/ResourcesView.tsx
Fixes #68. This adds the ability to create, edit and delete resources in the admin resource browser:
https://github.com/user-attachments/assets/51a88371-e98b-46df-a7b8-e94ea8620dae
=> Implement resource editing

package-lock.json, package.json, src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayView.tsx, src/utils/gamepad.ts
Fixes #76. This implements support for the new diff-based gamepad API and also implements the inspector view:
=> Implement new gamepad API and abstract out diffing

src/components/Display.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/displays/DisplayView.tsx
This adds a `cursor` property to `Display` and uses pointer/crosshair appropriately, depending on the context.
=> Customize display cursors

package-lock.json, package.json, src/screens/home/displays/DisplayView.tsx
Corresponding to https://github.com/ProjectLighthouseCAU/nighthouse/pull/15.
=> Bump nighthouse to 5.0.0 and update key events

src/components/ObjectInspectorTable.tsx, src/components/TimeInterval.tsx, src/hooks/useBreakpoint.ts, src/screens/home/admin/MonitorInspector.tsx, src/screens/home/admin/MonitorInspectorLampsCard.tsx, src/screens/home/admin/MonitorInspectorRoomCard.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/displays/DisplayInspectorInputCard.tsx
This fixes #83 and implements the days-hours-minutes-seconds format proposed in #73, along with fixing some sizing issues.
=> Improve the display and monitor inspector layout

package-lock.json, package.json, src/screens/home/displays/DisplayView.tsx
See https://github.com/ProjectLighthouseCAU/nighthouse/pull/16
=> Update nighthouse to 5.0.1 and new modifier API

package-lock.json, package.json, src/utils/gamepad.ts
See https://github.com/ProjectLighthouseCAU/nighthouse/pull/17 and https://github.com/ProjectLighthouseCAU/nighthouse/commit/cb415db9ee9d159384000da6ef6d9a96cb2434d6 for details.
=> Implement new 2D axis gamepad mapping

package-lock.json, package.json, src/components/Display.tsx, src/components/ObjectInspectorValue.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayView.tsx, src/screens/home/displays/helpers/InputConfig.ts
Sibling PR to https://github.com/ProjectLighthouseCAU/nighthouse/pull/18. This implements support for relative mouse events and pointer lock:
=> Provide relative mouse movements in events and support pointer lock

src/modals/QuickSwitcherModal.tsx
A small UX improvement that implements the up/down arrow keys for moving the selection in the quick switcher.
=> Implement key up/down shortcuts in quick switcher

src/components/RouteLink.tsx
=> Reimplement sidebar chevron using custom div

src/screens/home/HomeScreen.tsx
This is a small UX improvement that automatically scrolls to the top when pressing the hamburger button (in the compact/mobile layout).
=> Automatically scroll to the top when pressing menu button

src/components/DisplayContextMenu.tsx, src/hooks/useAdminStatus.ts, src/hooks/useLiveUser.ts, src/hooks/useVisibleRoutes.tsx
=> Add a context menu item for admins for setting a user to live

src/components/ApiTokenButton.tsx, src/components/UserSnippet.tsx, src/contexts/api/auth/AuthContext.tsx, src/modals/ApiTokenModal.tsx, src/screens/home/displays/DisplayInspectorApiTokenCard.tsx, src/screens/home/sidebar/Sidebar.tsx
This lets the user invalidate and regenerate their token from the UI.
=> Add button for cycling API token

src/contexts/api/auth/AuthContext.tsx, src/screens/home/displays/DisplayInspectorApiTokenCard.tsx
This exposes APIs for handling the tokens of all users (for admins)
=> Add methods for fetching and cycling any user's token

src/contexts/api/model/ModelContext.tsx, src/hooks/useFilteredDisplays.ts, src/hooks/useLiveUser.ts, src/hooks/useVisibleRoutes.tsx, src/screens/home/displays/DisplayGrid.tsx, src/screens/home/displays/DisplaysView.tsx
=> Store all users' metdata in model context again and abstract out filtering into `useFilteredDisplays`

src/contexts/api/auth/convert.ts
This fixes compatibility with older Heimdall versions.
=> Handle missing roles in API user gracefully

package-lock.json, package.json, src/components/ObjectInspectorValue.tsx, src/hooks/useLocalStorage.ts, src/screens/home/displays/DisplayInspector.tsx, src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayView.tsx, src/screens/home/displays/helpers/InputCapabilities.ts, src/screens/home/displays/helpers/InputConfig.ts, src/screens/home/displays/helpers/InputState.ts, src/utils/string.ts
This adds support for MIDI input, corresponding to https://github.com/ProjectLighthouseCAU/nighthouse/pull/19
=> Add support for MIDI input via Web MIDI

package-lock.json, package.json, src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayView.tsx, src/screens/home/displays/helpers/InputCapabilities.ts, src/screens/home/displays/helpers/InputConfig.ts, src/screens/home/displays/helpers/InputState.ts
This implements support for orientation and motion events on mobile devices, corresponding to https://github.com/ProjectLighthouseCAU/nighthouse/pull/20.
=> Add support for orientation and motion input

src/components/ObjectInspectorValue.tsx, src/utils/rot3.ts, src/utils/vec3.ts
Add corresponding utility interfaces and add a formatter for the object inspector.
=> Represent 3D vectors and rotations

package-lock.json, src/screens/home/displays/DisplayInspectorInputCard.tsx
=> Display the most recent motion/orientation events

src/components/ObjectInspectorValue.tsx, src/screens/home/displays/DisplayInspectorInputCard.tsx
This fixes a missing return and a field name that is too wide.
=> Fix issues with the orientation/motion display

src/components/DisplayActionsMenu.tsx, src/contexts/api/model/ModelContext.tsx
This adds a new display action that sends a black frame:
=> Add action for blacking out display

src/hooks/useFilteredDisplays.ts
This makes users easier to find.
=> Sort users case-insensitively

src/components/TitledCard.tsx, src/constants/LocalStorageKey.ts, src/hooks/useLocalStorage.ts, src/screens/home/admin/MonitorInspectorLampsCard.tsx, src/screens/home/admin/MonitorInspectorRoomCard.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/displays/DisplayInspectorActionsCard.tsx, src/screens/home/displays/DisplayInspectorApiTokenCard.tsx, src/screens/home/displays/DisplayInspectorInputCard.tsx, src/screens/home/displays/DisplayInspectorOptionsCard.tsx
=> Persist inspector collapse state in local storage

src/components/UnderConstruction.tsx, src/screens/home/admin/AdminView.tsx
...until we have a proper dashboard there (#120)
=> Use under construction view for admin view

src/contexts/displays/animator/AnimatorContext.tsx, src/contexts/displays/animator/run.ts, src/contexts/displays/animator/types/Animator.ts, src/contexts/displays/animator/types/AnimatorUpdate.ts, src/contexts/displays/animator/types/index.ts, src/hooks/useAnimator.ts, src/screens/home/displays/DisplayInspectorAnimatorCard.tsx
This fixes the race condition between the UI and animator updates by making all updates serializable.
=> Implement animator loop using updates

Dockerfile, src/components/AnimatorActionSnippet.tsx, src/contexts/displays/animator/AnimatorContext.tsx, src/contexts/displays/animator/tickAnimator.ts, src/contexts/displays/animator/types/AnimatorUpdate.ts, src/screens/home/displays/DisplayInspectorAnimatorCard.tsx, src/utils/pixelAlphabet.ts
Based on #149, this makes the animator scrubbable too.
=> Make the animator scrubbable

src/components/AnimatorActionSnippet.tsx, src/contexts/displays/animator/tickAnimator.ts, src/utils/pixelAlphabet.ts
This implements scrolling text, as suggested in #10:
https://github.com/user-attachments/assets/f9dcbaf8-32b5-4ea2-a737-61aebe2e0c7b
The text rendering is currently manually typesetting pixel characters, in the future we may either want to refine those or look into using some form of offscreen canvas rendering, to use the browser's text engine.
=> Implement scrolling text in animator

src/screens/home/displays/DisplayInspectorAnimatorCard.tsx, src/utils/rgb.ts
For consistency with the general display actions.
=> Add blackout animator action

src/constants/LocalStorageKey.ts, src/hooks/useCompactStatus.ts, src/hooks/useLocalStorage.ts, src/screens/home/HomeScreen.tsx, src/screens/home/admin/MonitorView.tsx, src/screens/home/displays/DisplayView.tsx, src/screens/home/displays/DisplaysToolbar.tsx, src/screens/home/displays/DisplaysView.tsx, src/screens/home/sidebar/SidebarRoutes.tsx
This fixes some usability issues with compact mode, notably the overflowing toolbar in the displays view and missing displays in searches.
=> Improve compact layout UI/UX

src/screens/home/sidebar/SidebarRoutes.tsx
=> Filter parent routes too in sidebar search

src/screens/home/admin/ResourcesContentsView.tsx, src/screens/home/admin/ResourcesTreeView.tsx, src/screens/home/admin/ResourcesView.tsx
This implements the resource browser layout in terms of the new fullScreen home content layout.
=> Improve resource browser layout

src/screens/home/displays/DisplayGrid.tsx
=> Disable text selection in display grid

src/screens/home/admin/ResourcesToolbar.tsx
=> Use compact refresh icon in admin resource view when in compact mode

src/screens/home/admin/MonitorView.tsx
These colors were swapped for some reason.
=> Fix inverted monitor criterion coloring
